### PR TITLE
Websocket disconnect

### PR DESCRIPTION
**Pull request by BrockReece**
As per our conversations yesterday, this is the starting place for the websocket disconnect message. Any feedback/contributions welcome, as it isn't very pretty at the moment.

This will also automatically install vue-toasted in the croud-layout plugin so that it can be rolled out to all projects using the plugin.

I would suggest that we finalise #19 first so we can use the translation factory for the wording. Claire seemed very excited by this prospect.

### CODE REVIEW

**Review by matthewerskine — APPROVED** [review]
I haven't tested but going by the way this was demonstrated and the implementation here, I am happy to see this feature merged in!

**Comment by BrockReece** [comment]
So slight change of plan with this PR.
We have now removed the user feedback whilst we finalise the design and the message, but we have added some analytics collections for reconnect and disconnect events. 

The analytics payload will include whether it has reconnected or disconnected, the timestamp of the disconnection, the time it took to reconnect and the username and id. From this we may be able to spot patterns based on time or specific users as well as collecting overall counts for how often this occurs. 

Obviously, if they have no connection at all, this will completely fail, but even this lack of collection will provide us with some insights.

**Review by kingy04 — APPROVED** [review]
The changes look good, Thanks

**Comment by BrockReece** [comment]
released in v1.12.0

**Pull request merged**
