### PR TITLE
C ui changes

### PR DESCRIPTION
**Pull request by kingy04**
Fixes console errors, changes animation logic, checks for user creds before making a promise, also checks for an email doesn't exist scenario when using forgot password, some styling adjustments and other minor tweaks

### CODE REVIEW

**Review by BrockReece — COMMENTED** [review]
Looks good, Nice use of the transition tags. Just a small one though, can we refactor the variables away from using snake_case to camelCase please. It's part of a repo wide change we need to make, but if we can do it as we go along that will help.

**Comment by kingy04** [comment]
no probs, thats done for you.

**Review by BrockReece — APPROVED** [review]
Perfect, thanks.

**Comment by kingy04** [comment]
I have added that code to a method as requested, there was no error to remove as it was the generic error one, however i have created two default messages for errors and reset email success, and added them to the standard component.. i agree that the messages should be the same. Cheers

**Comment by BrockReece** [comment]
Cool, It looks a lot cleaner and more reusable now, cheers for that.

**Comment by BrockReece** [comment]
Is this ready to merge now?

**Comment by kingy04** [comment]
All good now. Thanks.

**Pull request merged**
